`timescale 1ns/1ps
// Real-ROM boot investigation for the 2026-08-23 real-hardware bring-up
// symptom: on real hardware, the CPU runs continuously (confirmed via a
// VGA-color-coded sticky-bit debug tap -- see docs/ROADMAP.md/
// docs/LESSONS_LEARNED.md) but NEVER writes to any video RAM region or
// plain work RAM, even after 60+ seconds. The maincpu ROM interleave/byte
// order was independently re-derived and confirmed correct against
// MiSTer's own documented MRA `map` semantics (see
// releases/Samurai Aces (World).mra's maincpu <interleave> comment) --
// ruling out a ROM data-integrity bug. This test downloads the REAL,
// correctly-interleaved samuraia maincpu+audiocpu ROM (generated by
// sim/psikyo_top_tb/gen_real_rom.py from roms/samuraia.zip, NOT a synthetic
// test program) through the real HPS ioctl_download path, same as
// tb_psikyo_top.sv, then runs the real game's actual boot code with full
// simulation-only visibility (direct hierarchical taps -- no VGA-color
// guessing) into: cpu_rom_addr's progression (does the CPU explore new code
// or settle into a tight repeating loop), whether it EVER writes to any
// video RAM region or work RAM, and whether it ever requests/takes the
// vblank IRQ (rtl/cpu/tg68k/PROVENANCE.md's own still-open vector-fetch
// bug is a leading suspect for why real game code -- which relies on that
// IRQ, unlike every synthetic test program used before now -- might never
// reach real init code).
//
// This is NOT a pass/fail regression test (there's no independent oracle
// for "what should real samuraia boot code do") -- it's a diagnostic tool,
// same spirit as the real-hardware VGA-color debug builds but far cheaper
// to iterate on and far richer in visibility. Read its printed trace.
module tb_psikyo_top_realrom #(
	// Override via `vsim -GDL_BYTES_OVERRIDE=256` for a fast bisection run
	// when diagnosing where a full download stalls, without recompiling.
	parameter int DL_BYTES_OVERRIDE = 0
);

	logic clk = 0;
	always #5 clk = ~clk;
	logic reset;
	logic ce_pix = 1'b1;

	localparam logic [24:0] MAINCPU_BASE  = 25'h0000000;
	localparam logic [24:0] AUDIOCPU_BASE = 25'h0200000;
	localparam int MAINCPU_BYTES  = 'h80000;
	localparam int AUDIOCPU_BYTES = 'h20000;

	logic         ioctl_download;
	logic [15:0] ioctl_index;
	logic         ioctl_wr;
	logic [24:0] ioctl_addr;
	logic [7:0]  ioctl_dout;
	logic         ioctl_wait;

	logic [31:0] p1p2_in, dsw_in, coin_in;

	logic         ym_cs, ym_rd, ym_wr;
	logic [1:0]  ym_addr;
	logic [7:0]  ym_dout;
	logic [7:0]  ym_din;

	logic [8:0]  hcnt, vcnt;
	logic         hblank, vblank, hsync, vsync;
	logic [14:0] rgb;

	wire [15:0] SDRAM_DQ;
	logic [12:0] SDRAM_A;
	logic         SDRAM_DQML, SDRAM_DQMH;
	logic [1:0]  SDRAM_BA;
	logic         SDRAM_nCS, SDRAM_nWE, SDRAM_nRAS, SDRAM_nCAS, SDRAM_CLK, SDRAM_CKE;

	psikyo_top dut (
		// hiscore work-RAM port tied off (rtl/hiscore.v not in this TB)
		.hs_address(17'd0), .hs_data_in(8'd0), .hs_data_out(), .hs_read(1'b0), .hs_write(1'b0),
		// SH404 ports tied off (docs/phase2_sh404.md); this TB predates them
		.board_sh404(1'b0), .snd_latch_c00011(1'b0), .mcu_table_absent(1'b0),
		.mcu_table_we(1'b0), .mcu_table_waddr(8'd0), .mcu_table_wdata(8'd0),
		.clk(clk), .ce_pix(ce_pix), .reset(reset), .init(1'b0),
		.SDRAM_A(SDRAM_A), .SDRAM_DQML(SDRAM_DQML), .SDRAM_DQMH(SDRAM_DQMH),
		.SDRAM_BA(SDRAM_BA), .SDRAM_nCS(SDRAM_nCS), .SDRAM_nWE(SDRAM_nWE),
		.SDRAM_nRAS(SDRAM_nRAS), .SDRAM_nCAS(SDRAM_nCAS),
		.SDRAM_CLK(SDRAM_CLK), .SDRAM_CKE(SDRAM_CKE), .SDRAM_DQ(SDRAM_DQ),
		.ioctl_download(ioctl_download), .ioctl_index(ioctl_index),
		.ioctl_wr(ioctl_wr), .ioctl_addr(ioctl_addr), .ioctl_dout(ioctl_dout),
		.ioctl_wait(ioctl_wait),
		.p1p2_in(p1p2_in), .dsw_in(dsw_in), .coin_in(coin_in),
		.ym_cs(ym_cs), .ym_addr(ym_addr), .ym_rd(ym_rd), .ym_wr(ym_wr),
		.ym_dout(ym_dout), .ym_din(ym_din),
		.hcnt(hcnt), .vcnt(vcnt), .hblank(hblank), .vblank(vblank),
		.hsync(hsync), .vsync(vsync), .rgb(rgb)
	);

	assign ym_din = 8'h00;

	sdram_chip_model_wide chip (
		.clk(clk),
		.SDRAM_DQ(SDRAM_DQ), .SDRAM_A(SDRAM_A), .SDRAM_BA(SDRAM_BA),
		.SDRAM_nCS(SDRAM_nCS), .SDRAM_nWE(SDRAM_nWE), .SDRAM_nRAS(SDRAM_nRAS), .SDRAM_nCAS(SDRAM_nCAS)
	);

	logic [7:0] maincpu_rom  [0:MAINCPU_BYTES-1];
	logic [7:0] audiocpu_rom [0:AUDIOCPU_BYTES-1];
	initial $readmemh("maincpu_real_bytes.hex", maincpu_rom);
	initial $readmemh("audiocpu_real_bytes.hex", audiocpu_rom);

	// Bounded wait, unlike tb_psikyo_top.sv's own unbounded dl_write_byte --
	// added after a first run of THIS test (a much larger, sequential
	// 524288-byte download, unlike any prior test's handful of bytes) sat
	// for 7+ real minutes at ~0% CPU with `ioctl_wait` apparently never
	// deasserting: confirmed a genuine stall (near-zero process CPU time),
	// not just a slow download, but the exact stuck signal/cause wasn't
	// yet isolated when this guard was added. $fatal's exact byte
	// index/address pinpoints where it happens instead of hanging silently.
	task automatic dl_write_byte(input [24:0] addr, input [7:0] data);
		int wait_cycles;
		@(posedge clk);
		ioctl_addr = addr; ioctl_dout = data; ioctl_wr = 1'b1;
		@(posedge clk);
		ioctl_wr = 1'b0;
		wait_cycles = 0;
		while (ioctl_wait) begin
			@(posedge clk);
			wait_cycles++;
			if (wait_cycles > 10000) begin
				$display("[t=%0t] STALL: ioctl_wait stuck high for >10000 cycles writing addr=%h data=%h",
						   $time, addr, data);
				$fatal(1);
			end
		end
	endtask

	// ---- diagnostics: no VGA-color guessing, direct hierarchical taps ----
	logic any_write_seen = 1'b0;
	logic data_x_seen = 1'b0;
	logic irq_ever_pending = 1'b0;
	logic iack_ever_seen = 1'b0;
	logic [18:0] rom_addr_min = 19'h7FFFF, rom_addr_max = 0;

	always @(posedge clk) begin
		if (dut.u_core.pal_cpu_wel || dut.u_core.pal_cpu_weh) begin
			if (!any_write_seen) $display("[t=%0t] FIRST WRITE: palette addr=%h", $time, dut.u_core.pal_cpu_addr);
			any_write_seen <= 1'b1;
		end
		if (dut.u_core.vram0_cpu_wel || dut.u_core.vram0_cpu_weh) begin
			if (!any_write_seen) $display("[t=%0t] FIRST WRITE: vram0 addr=%h", $time, dut.u_core.vram0_cpu_addr);
			any_write_seen <= 1'b1;
		end
		if (dut.u_core.vram1_cpu_wel || dut.u_core.vram1_cpu_weh) begin
			if (!any_write_seen) $display("[t=%0t] FIRST WRITE: vram1 addr=%h", $time, dut.u_core.vram1_cpu_addr);
			any_write_seen <= 1'b1;
		end
		if (dut.u_core.vregs_cpu_wel || dut.u_core.vregs_cpu_weh) begin
			if (!any_write_seen) $display("[t=%0t] FIRST WRITE: vregs addr=%h", $time, dut.u_core.vregs_cpu_addr);
			any_write_seen <= 1'b1;
		end
		if (dut.u_core.workram_cpu_wel || dut.u_core.workram_cpu_weh) begin
			if (!any_write_seen) $display("[t=%0t] FIRST WRITE: workram addr=%h", $time, dut.u_core.workram_cpu_addr);
			any_write_seen <= 1'b1;
		end

		if (dut.u_core.u_cpu.irq_pending && !irq_ever_pending) begin
			$display("[t=%0t] vblank IRQ first asserted (irq_pending) cpu_rom_addr=%h", $time, dut.u_core.u_cpu.rom_addr);
			irq_ever_pending <= 1'b1;
		end
		// maincpu.sv now drives TG68KdotC_Kernel directly, so there is no
		// as_n -- an interrupt-acknowledge cycle is FC=3'b111 during a real
		// memory access, i.e. busstate != 2'b01 (mem_needed).
		if (dut.u_core.u_cpu.mem_needed && dut.u_core.u_cpu.fc == 3'b111 && !iack_ever_seen) begin
			$display("[t=%0t] IACK cycle first seen (FC=111, AS asserted) cpu_rom_addr=%h", $time, dut.u_core.u_cpu.rom_addr);
			iack_ever_seen <= 1'b1;
		end

		if (dut.u_core.cpu_rom_req) begin
			if (dut.u_core.cpu_rom_addr < rom_addr_min) rom_addr_min <= dut.u_core.cpu_rom_addr;
			if (dut.u_core.cpu_rom_addr > rom_addr_max) rom_addr_max <= dut.u_core.cpu_rom_addr;
		end

		// Distinguishes "X entered from a bad memory read (chip
		// model/download/burst-read bug)" from "X is genuinely generated
		// inside TG68K itself (a real vendored-core sim-fidelity gap)" --
		// the two would need completely different fixes.
		if (dut.u_core.u_cpu.rom_valid && $isunknown(dut.u_core.u_cpu.rom_data) && !data_x_seen) begin
			$display("[t=%0t] FIRST X ON rom_data FROM MEMORY: cpu_rom_addr=%h rom_data=%b", $time, dut.u_core.u_cpu.rom_addr, dut.u_core.u_cpu.rom_data);
			data_x_seen <= 1'b1;
		end
	end

	// Periodic status line -- shows whether cpu_rom_addr's [min,max] range
	// keeps growing (still exploring new code / legitimately running) or
	// has gone flat (settled into a bounded loop).
	logic [18:0] last_max = 0;
	always @(posedge clk) begin
		if ($time % 2_000_000 == 0 && $time > 0) begin
			$display("[t=%0t] status: rom_addr range=[%h,%h] (grew by %0d since last check) any_write_seen=%0d irq_pending=%0d iack_seen=%0d",
					   $time, rom_addr_min, rom_addr_max, rom_addr_max - last_max, any_write_seen, irq_ever_pending, iack_ever_seen);
			last_max <= rom_addr_max;
		end
	end

	// Independent hard watchdog, racing the whole test (not just the
	// post-download run phase) -- added after this test's first two runs
	// each sat for many real minutes/hours with near-zero CPU usage
	// (confirmed via Get-Process, not just "looked idle"): once with a
	// genuine SDRAM-model address-aliasing bug making the download loop
	// wait forever, once with a TG68K 'X' arithmetic warning flood that
	// never triggered dl_write_byte's own bounded wait guard because it
	// happened AFTER download, during the run phase. Neither prior failure
	// mode would have been caught by a timeout placed only after the
	// download, so this one covers the entire `initial` block from time 0.
	initial begin
		// ~20ms just for a full 655KB download at ~30ns/byte (2 setup edges
		// + >=1 wait-loop edge per dl_write_byte call), so budget generously
		// beyond that for real post-download execution time too.
		#100_000_000; // 100ms sim time
		$display("[t=%0t] WATCHDOG: simulation did not finish in time -- see sim/psikyo_top_tb/tb_psikyo_top_realrom.sv's own header for known prior failure modes", $time);
		$finish;
	end

	initial begin
		reset = 1;
		ioctl_download = 0; ioctl_index = 0; ioctl_wr = 0; ioctl_addr = 0; ioctl_dout = 0;
		p1p2_in = 32'hFFFFFFFF; dsw_in = 32'hFFFFFFFF; coin_in = 32'hFFFFFFFF;

		// sim/psikyo_top_tb/sdram_chip_model_wide.sv's whole address space --
		// see that file's own header for why the original, shared
		// sim/sdram_tb/sdram_chip_model.sv (8-bit row fold, 524288 words)
		// isn't usable here: maincpu and audiocpu's real base addresses
		// alias onto the same cells under that fold. 0xFFFF (not 0x0000)
		// matches releases/Samurai Aces (World).mra's own convention of
		// padding every reserved-but-unused ROM region with the byte 0xFF --
		// real boot code that reads/checksums maincpu's full 0x200000
		// reservation (not just its 0x80000 bytes of real content) sees the
		// same defined padding value real hardware does, not X.
		for (int i = 0; i < 16777216; i++) chip.mem[i] = 16'hFFFF;

		repeat (5) @(posedge clk);
		reset = 0;

		ioctl_download = 1;
		begin
			int maincpu_n, audiocpu_n, print_every;
			maincpu_n  = (DL_BYTES_OVERRIDE > 0) ? DL_BYTES_OVERRIDE : MAINCPU_BYTES;
			audiocpu_n = (DL_BYTES_OVERRIDE > 0) ? 0 : AUDIOCPU_BYTES;
			print_every = (DL_BYTES_OVERRIDE > 0) ? 1 : 65536;

			$display("Downloading real maincpu ROM (%0d bytes)...", maincpu_n);
			for (int i = 0; i < maincpu_n; i++) begin
				dl_write_byte(MAINCPU_BASE + i[24:0], maincpu_rom[i]);
				if (i % print_every == 0) $display("[t=%0t]  maincpu download: %0d/%0d bytes", $time, i, maincpu_n);
			end
			$display("Downloading real audiocpu ROM (%0d bytes)...", audiocpu_n);
			for (int i = 0; i < audiocpu_n; i++) begin
				dl_write_byte(AUDIOCPU_BASE + i[24:0], audiocpu_rom[i]);
				if (i % 16384 == 0) $display("[t=%0t]  audiocpu download: %0d/%0d bytes", $time, i, audiocpu_n);
			end
		end
		ioctl_download = 0;
		$display("[t=%0t] Download complete, releasing core from reset -- real boot starts now", $time);
		repeat (10) @(posedge clk);

		// Run for a generous stretch of real boot execution. Real hardware
		// stayed in the same bad state for 60+ real seconds (~5B clk_sys
		// cycles) -- far too many to simulate exhaustively, but if the CPU
		// is going to reach real init code at all, ordinary boot code
		// reaching it within low tens of millions of cycles is a reasonable
		// bar; if it hasn't by then, the periodic status lines above will
		// already show whether it's still exploring new addresses or has
		// gone flat (looping), which is the actionable signal either way.
		#40_000_000; // 40ms sim time = 4,000,000 clk cycles @ 10ns period

		$display("==== FINAL STATUS ====");
		$display("rom_addr range=[%h,%h] any_write_seen=%0d irq_pending=%0d iack_seen=%0d",
				   rom_addr_min, rom_addr_max, any_write_seen, irq_ever_pending, iack_ever_seen);
		if (any_write_seen)
			$display("PASS-ish: CPU reached real init code (at least one RAM write observed)");
		else
			$display("Still no RAM write observed -- see status trace above for whether rom_addr was still growing or had gone flat");

		$finish;
	end

endmodule
